title: "Sakshi Bhalla"
description: "Sakshi Bhalla is a political communication researcher at the University of Illinois Urbana-Champaign, studying the political economy of political information and its consequences for political behavior with computational and quantitative methods."
url: "https://sakshi-bhalla.github.io"
baseurl: ""
repository: "sakshi-bhalla/sakshi-bhalla.github.io"
lang: "en"

google_site_verification: "PwLXRenSrORmGHnZSNnkOdkj3aOLJHt9_KZvM9143oI"
google_analytics: "G-CC9LEWNPER"

author:
  name: "Sakshi Bhalla"
  short_name: "S. Bhalla"
  role: "PhD Candidate, Media & Communications · University of Illinois Urbana-Champaign"
  email: "sakshib3@illinois.edu"
  googlescholar: "https://scholar.google.com/citations?user=QewpAPIAAAAJ&hl=en"
  github: "https://github.com/sakshi-bhalla"
  bluesky: "https://bsky.app/profile/sakshi-bhalla.bsky.social"
  orcid: "https://orcid.org/0000-0002-6803-7657"
  linkedin: "https://www.linkedin.com/in/sb11"

markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - docs
  - README.md
  - vendor
